<a href="https://colab.research.google.com/github/ImitatedSky/Github-Colab/blob/1220/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
# 運算位置
al = torch.rand(3,4)
print(al.device) 
# 運算位置
device = (torch.device('cuda')if torch.cuda.is_available()else torch.device('cpu'))
print(device)
# tensor
al = torch.Tensor([1,2])
print(al.type())

cpu
cpu
torch.FloatTensor


In [8]:
a1 = torch.Tensor([1,2])
a2 = torch.Tensor([10,9])
print( a1 + a2)

tensor([11., 11.])


In [21]:
a = torch.randn(4)
print(a)
torch.add(a, 20)
print(a)
print(torch.add(a, 20))
print('-----')
b = torch.randn(4)
print(b)
c = torch.randn(4, 1)
print(c)
print('-----')
print(torch.add(b, c, alpha=10))

tensor([ 0.4613, -0.3627, -1.1922, -1.2197])
tensor([ 0.4613, -0.3627, -1.1922, -1.2197])
tensor([20.4613, 19.6373, 18.8078, 18.7803])
-----
tensor([-0.4829,  1.1731, -1.2740, -0.0894])
tensor([[0.1828],
        [0.5769],
        [0.5843],
        [0.4488]])
-----
tensor([[1.3446, 3.0007, 0.5536, 1.7382],
        [5.2864, 6.9424, 4.4953, 5.6799],
        [5.3598, 7.0159, 4.5687, 5.7533],
        [4.0054, 5.6615, 3.2143, 4.3989]])
