<a href="https://colab.research.google.com/github/ImitatedSky/Github-Colab/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# 運算位置
al = torch.rand(3,4)
print(al.device) 
# 運算位置
device = (torch.device('cuda')if torch.cuda.is_available()else torch.device('cpu'))
print(device)
# tensor
al = torch.Tensor([1,2])
print(al.type())

cpu
cuda
torch.FloatTensor


In [3]:
a1 = torch.Tensor([1,2])
a2 = torch.Tensor([10,9])
print( a1 + a2)

tensor([11., 11.])


In [7]:
a = torch.randn(4)
print(a)
torch.add(a, 20)
print(a)
print(torch.add(a, 20))
print('-----')
b = torch.randn(4)
print(b)
c = torch.randn(4, 1)
print(c)
print('-----')
print(torch.add(b, c, alpha=1))

tensor([ 0.1108,  1.7395,  0.6869, -1.9253])
tensor([ 0.1108,  1.7395,  0.6869, -1.9253])
tensor([20.1108, 21.7395, 20.6869, 18.0747])
-----
tensor([ 1.8511, -1.5224, -0.1772,  0.4665])
tensor([[-0.5175],
        [-1.2173],
        [-1.5547],
        [ 0.6473]])
-----
tensor([[ 1.3336, -2.0398, -0.6947, -0.0510],
        [ 0.6338, -2.7397, -1.3945, -0.7508],
        [ 0.2963, -3.0771, -1.7319, -1.0882],
        [ 2.4984, -0.8750,  0.4701,  1.1138]])


In [5]:
# 1123