<a href="https://colab.research.google.com/github/ImitatedSky/Github-Colab/blob/1220/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# 運算位置
al = torch.rand(3,4)
print(al.device) 
# 運算位置
device = (torch.device('cuda')if torch.cuda.is_available()else torch.device('cpu'))
print(device)
# tensor
al = torch.Tensor([1,2])
print(al.type())

cpu
cpu
torch.FloatTensor


In [3]:
a1 = torch.Tensor([1,2])
a2 = torch.Tensor([10,9])
print( a1 + a2)

tensor([11., 11.])


In [4]:
a = torch.randn(4)
print(a)
torch.add(a, 20)
print(a)
print(torch.add(a, 20))
print('-----')
b = torch.randn(4)
print(b)
c = torch.randn(4, 1)
print(c)
print('-----')
print(torch.add(b, c, alpha=10))

tensor([ 0.2317,  0.3182, -1.1399, -0.4502])
tensor([ 0.2317,  0.3182, -1.1399, -0.4502])
tensor([20.2317, 20.3182, 18.8601, 19.5498])
-----
tensor([-0.5260, -0.0182, -0.1894, -0.7842])
tensor([[1.2666],
        [0.5011],
        [0.0338],
        [0.4274]])
-----
tensor([[12.1397, 12.6475, 12.4764, 11.8815],
        [ 4.4850,  4.9928,  4.8217,  4.2269],
        [-0.1879,  0.3199,  0.1488, -0.4461],
        [ 3.7482,  4.2560,  4.0848,  3.4900]])
