<a href="https://colab.research.google.com/github/ImitatedSky/Github-Colab/blob/1220/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch

In [7]:
# 運算位置
al = torch.rand(3,4)
print(al.device) 
# 運算位置
device = (torch.device('cuda')if torch.cuda.is_available()else torch.device('cpu'))
print(device)
# tensor
al = torch.Tensor([1,2])
print(al.type())

cpu
cpu
torch.FloatTensor


In [8]:
a1 = torch.Tensor([1,2])
a2 = torch.Tensor([10,9])
print( a1 + a2)

tensor([11., 11.])


In [9]:
a = torch.randn(4)
print(a)
torch.add(a, 20)
print(a)
print(torch.add(a, 20))
print('-----')
b = torch.randn(4)
print(b)
c = torch.randn(4, 1)
print(c)
print('-----')
print(torch.add(b, c, alpha=10))

tensor([-1.3791, -0.8328,  0.5748,  1.6875])
tensor([-1.3791, -0.8328,  0.5748,  1.6875])
tensor([18.6209, 19.1672, 20.5748, 21.6875])
-----
tensor([-1.6877, -1.5316, -0.1381, -1.7000])
tensor([[ 0.8688],
        [-0.3548],
        [-0.8999],
        [-1.0977]])
-----
tensor([[  7.0004,   7.1565,   8.5500,   6.9881],
        [ -5.2356,  -5.0795,  -3.6860,  -5.2479],
        [-10.6870, -10.5309,  -9.1374, -10.6993],
        [-12.6644, -12.5083, -11.1148, -12.6767]])
